#!/usr/bin/env bash

# Usage:
# BOT_PASS=<dotty-bot password> ./genDocs

set -e
# set extended glob, needed for rm everything but x
shopt -s extglob

# make sure that BOT_PASS is set
if [ -z "$BOT_PASS" ]; then
    echo "Error: BOT_PASS env unset, unable to push without password" 1>&2
    exit 1
fi

echo "Working directory: $PWD"

# get the ivy2 cache
ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"

echo "Success Doc"
