#!/usr/bin/env bash

# Usage:
# ./sbt <cmd>

CMD="$1"

if [ -z "$CMD" ]; then
  echo "Error: missing sbt command"
  exit 1
fi

# get the ivy2 cache
ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"

echo "Success sbt $CMD"
