#!/usr/bin/env bash

# Usage:
# SONATYPE_USER=<sonatype user> SONATYPE_PW=<sonatype pw> PGP_PW=<pgp pw> ./sbtPublish <publish cmd>

# Release command:
RELEASE_CMD="$1"

if [ -z "$SONATYPE_USER" ] || [ -z "$SONATYPE_PW" ] || [ -z "$PGP_PW" ]; then
    echo "Error: SONATYPE_USER, SONATYPE_PW or PGP_PW env unset"
    exit 1
fi

if [ ! "$NIGHTLYBUILD" = "yes" ] && [ ! "$RELEASEBUILD" = "yes" ]; then
    echo "Neither NIGHTLYBUILD nor RELEASEBUILD env var set to \"yes\""
    exit 1
fi

if [ -z "$RELEASE_CMD" ]; then
  echo "Error: missing publish command"
  exit 1
fi

# get the ivy2 cache
ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"

echo "Success sbtPublish $RELEASE_CMD"
