kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - echo "Cloning submodules"
  # - git submodule update --init --jobs 3

- name: test
  image: lampepfl/dotty:2018-10-01
  group: tests
  commands:
  - sleep 4
  # - cp -R . /tmp/1/ && cd /tmp/1/
  # - ./project/scripts/sbt ";compile ;test"
  # - ./project/scripts/cmdTests

- name: test bootstrapped
  image: lampepfl/dotty:2018-10-01
  group: tests
  commands:
  - sleep 4
  # - cp -R . /tmp/2/ && cd /tmp/2/
  # - ./project/scripts/sbt ";dotty-bootstrapped/compile ;dotty-bootstrapped/test"
  # - ./project/scripts/bootstrapCmdTests

- name: test sbt
  image: lampepfl/dotty:2018-10-01
  group: tests
  commands:
  - sleep 4
  # - cp -R . /tmp/3/ && cd /tmp/3/
  # - ./project/scripts/sbt sbt-dotty/scripted
  when:
    # sbt scripted tests are slow and only run on nightly or release (a.k.a. promote)
    event:
    - tag
    - promote

# DOCUMENTATION:
- name: documentation
  image: lampepfl/dotty:2018-10-01
  commands:
  - ./project/scripts/genDocs
  environment:
    BOT_TOKEN:
      from_secret: bot_token
  when:
    event:
    - push
    # We only generate the documentation for the master branch
    branch:
    - master

# PUBLISHING:
# Publishing expect NIGHTLYBUILD or RELEASEBUILD to be set. See dottyVersion in Build.scala
- name: publish nightly
  image: lampepfl/dotty:2018-10-01
  environment:
    NIGHTLYBUILD: yes
    SONATYPE_USER:
      from_secret: sonatype_user
    SONATYPE_PW:
      from_secret: sonatype_pw
    PGP_PW:
      from_secret: pgp_pw
    PGP_SECRET:
      from_secret: pgp_secret
  commands:
  - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
  when:
    target:
    - nightly

- name: publish release
  image: lampepfl/dotty:2018-10-01
  environment:
    RELEASEBUILD: yes
    SONATYPE_USER:
      from_secret: sonatype_user
    SONATYPE_PW:
      from_secret: sonatype_pw
    PGP_PW:
      from_secret: pgp_pw
    PGP_SECRET:
      from_secret: pgp_secret
  commands:
  # Produces dotty-version.{tar.gz, zip}
  - ./project/scripts/sbt dist-bootstrapped/packArchive
  - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
  when:
    event:
    - tag

# Publish dotty-version.{tar.gz, zip} to GitHub Release
- name: github release
  image: plugins/github-release
  settings:
    files: dist-bootstrapped/target/dotty-*
    checksum: sha256
    draft: true
    api_key:
      from_secret: github_token
  when:
    event:
    - tag

- name: publish sbt release
  image: lampepfl/dotty:2018-10-01
  environment:
    RELEASEBUILD: yes
    SONATYPE_USER:
      from_secret: sonatype_user
    SONATYPE_PW:
      from_secret: sonatype_pw
    PGP_PW:
      from_secret: pgp_pw
    PGP_SECRET:
      from_secret: pgp_secret
  commands:
  - ./project/scripts/sbtPublish ";sbt-dotty/publishSigned ;sonatypeRelease"
  when:
    target:
    - sbt_release

# NOTIFICATIONS:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dotty
  when:
    status:
    - failure
    event:
    - push
    - tag
    - deployment
