pipeline:
  test:
    image: lampepfl/dotty:2017-08-30
    commands:
      - echo "${CI_TEST}"
      #- ./project/scripts/sbt "${CI_TEST}"
    when:
      branch: master

  publish_nightly:
    image: lampepfl/dotty:2017-08-30
    commands:
      - ./project/scripts/sbt ";clean ;publishLocal" "${CI_PUBLISH}"
      - ./project/scripts/sbt "sbt-dotty/scripted source-dependencies/*" "${CI_PUBLISH}"
      - NIGHTLYBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: nightly

  publish_release:
    image: lampepfl/dotty:2017-08-30
    commands:
      - ./project/scripts/sbt ";clean ;publishLocal" "${CI_PUBLISH}"
      - ./project/scripts/sbt "sbt-dotty/scripted source-dependencies/*" "${CI_PUBLISH}"
      - RELEASEBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: release

  publish_sbt_release:
    image: lampepfl/dotty:2017-08-30
    commands:
      - RELEASEBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";sbt-dotty/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: sbt_release

  documentation:
    image: lampepfl/dotty:2017-08-30
    commands:
      - ./project/scripts/genDocs "${CI_PUBLISH}" $BOT_PASS
    secrets: [ bot_pass ]
    when:
      branch: master
      event: push

  slack:
    image: plugins/slack
    channel: drone-test
    secrets: [ slack_webhook ]
    when:
      branch: master
      status: [ success, failure ]
      event: [ push, deployment ]

matrix:
  include:
    - CI_TEST: legacyTests
      CI_PUBLISH: true
    - CI_TEST: ;test;sbt-dotty/scripted compilerReporter/*;sbt-dotty/scripted discovery/*;sbt-dotty/scripted sbt-dotty/*
      CI_PUBLISH: false
    - CI_TEST: dotty-bootstrapped/test
      CI_PUBLISH: false
    - CI_TEST: ;set bootstrapOptimised in ThisBuild := true ;dotty-bootstrapped/test
      CI_PUBLISH: false
